In [2]:
print("hello")

hello


# Heading1
* list1
* list2
[link](http://google.com)

$a = \sum{i = 1}{n}x$

In [ ]:
print('hello, world!')

In [4]:
a = 5
print(id(a))
a = "hello"
print(id(a))


10968928
139833668775584


In [ ]:
a = 5
b = 7
c = a + b
print(c)

In [6]:
a = [1, 2, 3]
print(a, id(a))
a.append(6)
print(a, id(a))


[1, 2, 3] 139833723368264
[1, 2, 3, 6] 139833723368264


# heading of some topic

In [ ]:
a = 5
print(id(a))
a = 'asd'
print(id(a))
b = [1, 2, 3]
print(id(b))
b.append(4)
print(id(b))


In [7]:
2 ** 5

32

In [8]:
3 / 4

0.75

In [12]:
10 ** 1000 / 5


OverflowError: integer division result too large for a float

In [13]:
str = 'pre aspera ad astra'
str = "pre aspera ad' \"astra\""
print(str)

pre aspera ad' "astra"


In [14]:
a = 5
b = 7
str = "a: {}; b: {}".format(a, b)
print(str)

a: 5; b: 7


In [15]:
dir("str")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [16]:
help("".replace)

Help on built-in function replace:

replace(...) method of builtins.str instance
    S.replace(old, new[, count]) -> str
    
    Return a copy of S with all occurrences of substring
    old replaced by new.  If the optional argument count is
    given, only the first count occurrences are replaced.



In [17]:
l = ["1", "2", "3"]
dir(l)



['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [18]:
dir([])
a = [5, 2, 1, 4, 5]
print(a)
a.append(7)
print(a)
a.reverse()
print(a)
a.sort()
print(a)
b = a.pop()
print(a, b)

[5, 2, 1, 4, 5]
[5, 2, 1, 4, 5, 7]
[7, 5, 4, 1, 2, 5]
[1, 2, 4, 5, 5, 7]
[1, 2, 4, 5, 5] 7


In [23]:
d = {'surname': 'ivanoff'}
d['name'] = 'Misha'
d['age'] = 22
print(d)


{'surname': 'ivanoff', 'name': 'Misha', 'age': 22}


In [24]:
print(d['name'])
print('name' in d)

#print(d["names"])
print(d.get('names', 'not found'))

del d['surname']
print(d)

Misha
True
not found
{'name': 'Misha', 'age': 22}


In [25]:
def my_sum(a, b = 3, c = 1): 
    '''
    sum of 2 digits
    '''
    result = a + b
    return result

print(my_sum(5))
print(my_sum(5, 8))
help(my_sum)

8
13
Help on function my_sum in module __main__:

my_sum(a, b=3, c=1)
    sum of 2 digits



In [ ]:
if not 'name1' in d or False:
    print('ok')

In [29]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
sum = 0
r = range(0, 10)
lst = list(r)
for i in r:
    print(i)
    sum = sum + i
print(sum)



0
1
2
3
4
5
6
7
8
9
45


In [32]:
l = ['cat', 'dog', 'elephant']
for key, value in enumerate(l):
    print('{}: {}'.format(key, value))

a, b = 2, 3
print(a)
print(b)
    
for key, value in d.items():
    print('key: {} value: {}'.format(key, value))

0: cat
1: dog
2: elephant
2
3
key: name value: Misha
key: age value: 22


In [43]:
l = list(range(50))

print(l)
print(l[-5:-10:-2])



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[45, 43, 41]


In [ ]:
print(l[-1])
print(l[0:10])
print(l[::3])
print(l[-1:-10:-2])


In [47]:
lst = list(range(0, 10))
print(lst)
lst1 = [2 ** x for x in lst if x % 2 == 0]
print(lst1)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 16, 64, 256]
25


In [ ]:
l = []
for i in range(10):
    l.append(2 ** i)
print(l)

f = lambda x: 2 ** x

print(f(5))
lst1 = [f(i) for i in range(10) if i % 3 == 0]
print(lst, lst1)

l = list(range(100))
nl = [i for i in l if i % 2 == 1]
print(nl)

In [53]:
lst = list(map(lambda x: 2 ** x if x % 3 == 0 and x > 10 else 0, list(range(20))))
print(lst)



[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4096, 0, 0, 32768, 0, 0, 262144, 0]


In [ ]:
import numpy as n

a = n.zeros(5)
a

In [54]:
import numpy as np

a = np.array([0, 1, 2, 3])
print(a)

a = np.zeros(5)
print(a)

a += 1
print(a)

# Return evenly spaced values within a given interval
b = np.arange(0, 10, 2)
print(b)

print(a + b)

[0 1 2 3]
[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]
[0 2 4 6 8]
[ 1.  3.  5.  7.  9.]
